import Link from "next/link";
import { ArrowRight, ChevronDown, LockKeyhole, Map, Play, ScanLine, Shield } from "lucide-react";

const facts = ["3—6 jogadores", "90—120 minutos", "18+", "Cooperativo"];

export default function Home() {
  return <main>
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6">
      <Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center border border-[#c7a96b]/50 text-[#c7a96b]"><LockKeyhole size={16}/></span><span className="text-xs tracking-[.18em] text-[#f4f1e8]">OMN / ATLAS</span></Link>
      <div className="hidden items-center gap-7 text-sm text-[#99a1ae] md:flex"><Link href="/historia" className="hover:text-[#f4f1e8]">A operação</Link><Link href="/como-funciona" className="hover:text-[#f4f1e8]">Como funciona</Link><Link href="/entrar" className="hover:text-[#f4f1e8]">Entrar</Link></div>
      <Link href="/ativar" className="button-ghost flex items-center gap-2 text-sm">Ativar jogo <ArrowRight size={15}/></Link>
    </nav>
    <section className="mx-auto grid min-h-[calc(100vh-92px)] max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.08fr_.92fr]">
      <div><p className="eyebrow mb-6">Dossiê 00 / Transmissão segura</p><h1 className="serif max-w-3xl text-6xl leading-[.88] tracking-tight md:text-8xl">À meia-noite,<br/><span className="text-[#c7a96b]">o segredo</span><br/>muda de mãos.</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-[#99a1ae]">Uma festa de máscaras. Uma mansão blindada. Um leilão que nunca deveria existir. Reúnam sua equipe e recuperem a Chave Atlas antes que a cidade descubra o que está em jogo.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/ativar" className="button-primary flex items-center gap-3">Inserir código do jogo <ArrowRight size={17}/></Link><Link href="/historia" className="button-ghost flex items-center gap-3">Conhecer a operação <Play size={15}/></Link></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-xs uppercase tracking-[.16em] text-[#99a1ae]">{facts.map(f=><span key={f}>{f}</span>)}</div></div>
      <div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-5 border border-[#c7a96b]/10"/><div className="panel relative aspect-[.8] overflow-hidden p-6"><div className="absolute inset-0 bg-[radial-gradient(circle_at_60%_35%,rgba(120,183,208,.16),transparent_24%),linear-gradient(135deg,transparent_35%,rgba(199,169,107,.08))]"/><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between text-[10px] uppercase tracking-[.2em] text-[#99a1ae]"><span>Arquivo Atlas</span><span>03:17:42</span></div><div className="mx-auto grid h-44 w-44 place-items-center rounded-full border border-[#c7a96b]/40"><div className="grid h-28 w-28 place-items-center rounded-full border border-[#78b7d0]/50"><ScanLine className="text-[#78b7d0]" size={40}/></div></div><div><p className="eyebrow">Mansão Vesper / Acesso restrito</p><p className="serif mt-2 text-3xl">A chave está em algum lugar da noite.</p><div className="mt-5 flex items-center gap-2 text-xs text-[#99a1ae]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#9b2638]"/> sinal interceptado · aguardando equipe</div></div></div></div></div>
    </section>
    <section className="border-y border-white/10 bg-[#0e1219]/60"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-12 md:grid-cols-3"><Feature icon={<Map/>} title="A mesa é parte da missão" text="Documentos, envelopes e marcadores físicos conduzem cada descoberta."/><Feature icon={<Shield/>} title="Cada escolha deixa marca" text="Rotas, votos e falhas alteram o estado da operação em tempo real."/><Feature icon={<ChevronDown/>} title="Nenhum final é garantido" text="Seis desfechos possíveis. A verdade depende de quem vocês decidem proteger."/></div></section>
    <footer className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-10 text-xs text-[#99a1ae] md:flex-row md:justify-between"><span>Obra de ficção para entretenimento adulto.</span><span>Operação da Meia-Noite · A Chave Atlas</span></footer>
  </main>;
}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <div className="panel p-5"><div className="mb-5 text-[#c7a96b]">{icon}</div><h2 className="serif text-2xl">{title}</h2><p className="mt-2 text-sm leading-relaxed text-[#99a1ae]">{text}</p></div> }
